@host = http://localhost
@port = 3000

@url = {{host}}:{{port}}

### GET all users
GET {{url}}/kategoria
Content-Type: application/json

### get one record from table by id
GET {{url}}/orders/3
Content-Type: application/json

### post new record to table
POST {{url}}/termek
Content-Type: application/json

{
    "termekNev": "Snickers",
    "nettoAr": 400,
    "egyseg": "db",
    "kategoriaId": 3
}


### UPDATE record from :table by :id

PATCH {{url}}/kategoria/12
Content-Type: application/json

{
    "kategoriaNev": "Teszt modositas"
}



### login
POST {{url}}/users/login
Content-Type: application/json

{
    "email": "teszt@gmail.com",
    "password": "123456"
}


### Regisztracio
POST {{url}}/users/registration
Content-Type: application/json

{
    "name": "Pista",
    "email": "nemmondommeg@gmail.com",
    "password": "Titok1234567",
    "confirm": "Titok1234567"
}


### get one record with operator
GET {{url}}/users/id/lt/4
Content-Type: application/json


### SEND email
POST {{url}}/sendmail
Content-Type: application/json

{
    "template": "registration",
    "to": "nagyapatiszilard@turr.hu",
    "subject": "Regisztráció",
    "data": {
        "name": "Rákos Roland",
        "url": "localhost",
        "email": "teszt123@1251235.hu",
        "company": "Oláh család pizzéria",
        "password": "nemmondommeg"
    }
}